FROM nginx:1.16
RUN chmod 777 -R /var/cache/nginx/
COPY nginx/nginx.conf /opt/nginx/nginx.conf
COPY nginx/default.conf /opt/nginx/conf.d/default.conf

COPY ./apps/ /opt/nginx/www/
RUN echo '# empty prometheus metrics response' > /opt/nginx/www/metrics

RUN adduser -q --gecos '' --disabled-login --shell /bin/false moov
USER moov

EXPOSE 8080
ENTRYPOINT ["nginx"]
CMD ["-c", "/opt/nginx/nginx.conf"]
